export function buildSampleSetup() {
  return {
    installCommand: "openclaw plugins install openclaw-deal-hunter",
    configSnippet: {
      plugins: {
        entries: {
          "openclaw-deal-hunter": {
            enabled: true,
            config: {
              maxConcurrent: 8,
              maxBytesPerResponse: 1_048_576,
              defaultMaxRpsPerHost: 1,
              allowedHosts: ["*.example.com"],
              blockedHosts: ["localhost"],
              fetcher: "local",
            },
          },
        },
      },
    },
    discoveryExamples: {
      manual: {
        plugins: {
          entries: {
            "openclaw-deal-hunter": {
              enabled: true,
              config: {
                allowedHosts: ["www.bestbuy.com", "www.target.com"],
                discovery: {
                  enabled: true,
                  provider: "manual",
                  maxFetches: 5,
                  allowedHosts: ["www.bestbuy.com", "www.target.com"],
                },
              },
            },
          },
        },
      },
      firecrawlSearch: {
        plugins: {
          entries: {
            "openclaw-deal-hunter": {
              enabled: true,
              config: {
                firecrawlApiKey: "fc-REPLACE_ME",
                discovery: {
                  enabled: true,
                  provider: "firecrawl-search",
                  maxSearchResults: 5,
                  maxFetches: 5,
                  allowedHosts: ["www.bestbuy.com", "www.target.com"],
                },
              },
            },
          },
        },
      },
    },
    reviewExamples: {
      queueOnly: {
        plugins: {
          entries: {
            "openclaw-deal-hunter": {
              enabled: true,
              config: {
                llmReview: {
                  mode: "queue",
                  lowConfidenceThreshold: 45,
                  maxReviewsPerScan: 3,
                },
              },
            },
          },
        },
      },
      autoAssist: {
        plugins: {
          entries: {
            "openclaw-deal-hunter": {
              enabled: true,
              config: {
                llmReview: {
                  mode: "auto_assist",
                  lowConfidenceThreshold: 35,
                  maxReviewsPerScan: 2,
                  allowIdentityRewrite: true,
                  allowPriceRewrite: false,
                },
              },
            },
          },
        },
      },
    },
    allowlist: [
      "openclaw-deal-hunter",
      "deal_watch_list",
      "deal_template_list",
      "deal_watch_add",
      "deal_watch_add_template",
      "deal_watch_update",
      "deal_watch_set_enabled",
      "deal_watch_search",
      "deal_watch_taxonomy",
      "deal_host_report",
      "deal_saved_view_list",
      "deal_saved_view_create",
      "deal_saved_view_update",
      "deal_saved_view_run",
      "deal_saved_view_dashboard",
      "deal_saved_view_delete",
      "deal_view_scan",
      "deal_view_report",
      "deal_watch_bulk_update",
      "deal_view_bulk_update",
      "deal_watch_tag",
      "deal_watch_dedupe",
      "deal_watch_export",
      "deal_watch_import",
      "deal_watch_import_url",
      "deal_watch_remove",
      "deal_scan",
      "deal_fetch_url",
      "deal_extraction_debug",
      "deal_evaluate_text",
      "deal_help",
      "deal_quickstart",
      "deal_report",
      "deal_digest",
      "deal_workflow_action_queue",
      "deal_workflow_portfolio",
      "deal_workflow_triage",
      "deal_workflow_cleanup",
      "deal_workflow_best_opportunities",
      "deal_health",
      "deal_discovery_backlog",
      "deal_discovery_policy",
      "deal_review_policy",
      "deal_history",
      "deal_alerts",
      "deal_trends",
      "deal_top_drops",
      "deal_market_check",
      "deal_market_check_candidates",
      "deal_discovery_report",
      "deal_discovery_search",
      "deal_discovery_fetch",
      "deal_discovery_run",
      "deal_discovery_import",
      "deal_product_groups",
      "deal_best_price_board",
      "deal_llm_review_queue",
      "deal_llm_review_run",
      "deal_llm_review_apply",
      "deal_watch_insights",
      "deal_watch_identity",
      "deal_schedule_advice",
      "deal_doctor",
      "deal_sample_setup",
    ],
    examplePrompts: [
      "Use deal_help and tell me the best first-run workflow for this plugin.",
      "Use deal_quickstart and give me the safest first-run checklist for this plugin.",
      "Use deal_template_list and recommend the best starter template for my first watch.",
      "Use deal_watch_add_template in dry-run mode to prepare a restock_signal watch for https://example.com/product.",
      "Use deal_watch_add to add a watch for https://example.com/product and then use deal_scan with commit true.",
      "Use deal_watch_taxonomy and suggest the best saved views I should create from my current groups and tags.",
      "Use deal_host_report and tell me which retailer hosts are driving the most signals right now.",
      "Use deal_watch_search to show me disabled watches and any watches currently showing threshold or keyword signals.",
      "Use deal_saved_view_create to save a view for my GPU watches with active signals, then run it.",
      "Use deal_saved_view_dashboard so I can see which saved views currently deserve attention first.",
      "Use deal_saved_view_update to rename my GPU view and tighten the selector to only enabled watches with snapshots.",
      "Use deal_watch_tag to tag my GPU watches and group them under pc-build.",
      "Use deal_view_scan with commit true for my GPU alerts saved view, then summarize what changed.",
      "Use deal_view_report for my GPU alerts saved view so I get alerts, trends, drops, and best opportunities in one call.",
      "Use deal_digest for my GPU alerts saved view so I get a concise announcement-ready summary I can post directly.",
      "Use deal_workflow_action_queue for my GPU alerts saved view so I know exactly what to do next.",
      "Use deal_view_bulk_update in dry-run mode to add the tag featured to all watches in my GPU alerts saved view.",
      "Use deal_watch_dedupe in dry-run mode and show me any likely duplicate watches before I clean up the list.",
      "Use deal_alerts to show me the hottest current signals, then use deal_history for the most interesting watch.",
      "Use deal_top_drops and deal_trends to show me the strongest current deals with context.",
      "Use deal_market_check for my best-looking deal and show me whether the current watch is actually the best price in my store.",
      "Use deal_market_check_candidates with a few retailer URLs I provide and tell me whether any look like the same product before I add them.",
      "Use deal_discovery_report for one watch so I can see the best candidates, blocked results, duplicates, and import recommendations in one compact summary.",
      "Use deal_discovery_search for one watch and a few allowed retailer hosts so I can get bounded discovery candidates before fetching them.",
      "Use deal_discovery_run with a few explicit retailer URLs and prepare import recommendations without adding anything yet.",
      "Use deal_discovery_import in dry-run mode so I can preview which discovery candidates would become new watches.",
      "Use deal_product_groups to cluster likely same-product watches and show me which groups have meaningful internal price spread.",
      "Use deal_best_price_board to rank where my current best-known internal prices are hiding.",
      "Use deal_llm_review_queue to prepare any weak extraction or unresolved identity cases for optional manual or llm-task review.",
      "Use deal_llm_review_run for one queued candidate if I want explicit JSON output from my configured model.",
      "Use deal_llm_review_apply in dry-run mode to show how one reviewed JSON result would patch my watch snapshot.",
      "Use deal_watch_insights for my most volatile watch and explain whether it looks real or noisy.",
      "Use deal_watch_identity for my best current deal and tell me whether any other watches appear to be the same product.",
      "Use deal_workflow_triage to tell me what changed, what matters, what is noisy, and what I should review first.",
      "Use deal_workflow_best_opportunities to rank the top real deals, suspicious glitches, and strongest same-product spreads.",
      "Use deal_discovery_backlog to tell me which watches most need broader retailer coverage before I start discovery work.",
      "Use deal_discovery_policy to show whether discovery is off, manual-only, or using bounded Firecrawl search.",
      "Use deal_sample_setup and show me the manual discovery config example plus the safer queue-only review policy example.",
      "Use deal_review_policy to show whether scan-time review is off, queue-only, or auto-assist.",
      "Use deal_workflow_cleanup to show me duplicates, disabled stale watches, weak extraction cases, and noisy watches.",
      "Use deal_workflow_portfolio to give me an executive dashboard of my current watch portfolio.",
      "Use deal_digest to give me a short summary of what changed and what matters right now.",
      "Use deal_workflow_action_queue to rank my next actions across alerts, cleanup, discovery, and review.",
      "Use deal_watch_export to back up my watches, then prepare a deal_watch_import dry run for another workspace.",
      "Fetch a shared JSON watchlist with deal_watch_import_url in dry-run mode and show me what would change.",
    ],
    cronExample:
      "openclaw cron add --name \"Deal scan\" --cron \"0 * * * *\" --session isolated --message \"Run deal_scan with commit true for all enabled watches. Summarize any alerts.\" --announce",
  };
}

export function buildQuickstartGuide() {
  return {
    installCommand: "openclaw plugins install openclaw-deal-hunter",
    firstRunChecklist: [
      "Enable the plugin and allow the tools you want your agent to use.",
      "Set allowedHosts for the retailer domains you trust most.",
      "Use deal_template_list if you want a faster template-driven first watch instead of building fields manually.",
      "Use deal_watch_add to create the first watch.",
      "Use deal_watch_taxonomy once the watchlist grows so you can see which groups, tags, and saved views deserve cleanup.",
      "Use deal_host_report when you want a retailer-level view of signal density and scan cadence.",
      "Use deal_saved_view_create for repeat searches once your watchlist grows beyond a few items.",
      "Use deal_saved_view_update to keep saved views aligned with how you actually manage the watchlist.",
      "Use deal_watch_tag or deal_watch_bulk_update once you have enough watches to organize by tag or group.",
      "Use deal_view_scan or deal_view_report when you want to work on one saved slice instead of the whole portfolio.",
      "Run deal_scan with commit true to capture the first snapshot.",
      "Use deal_alerts, deal_trends, deal_market_check, deal_watch_identity, deal_workflow_triage, and deal_report to inspect what changed.",
      "Use deal_market_check_candidates if you want to compare one watched product against a few explicit retailer URLs without adding them yet.",
      "Use deal_discovery_backlog to prioritize which watches deserve discovery effort first.",
      "Use deal_discovery_policy before enabling provider-backed discovery so you can verify the active host and budget constraints.",
      "Use deal_discovery_report when you want a compact discovery decision summary before drilling into raw candidate arrays or import previews.",
      "Enable discovery in manual mode when you want bounded candidate evaluation and import preview from explicit URLs only.",
      "Enable discovery in firecrawl-search mode only when you also have explicit retailer hosts you trust for bounded search.",
      "Use deal_product_groups and deal_best_price_board after you have same-product coverage across multiple retailers.",
      "Use deal_llm_review_queue when you want optional model-assisted review without making Deal Hunter itself depend on another plugin tool.",
      "Use deal_llm_review_run when you want to execute one queued review explicitly through the embedded OpenClaw runtime.",
      "Use deal_llm_review_apply in dry-run mode before writing reviewed fields back into a watch snapshot.",
      "Use deal_watch_export before large watchlist edits or migration.",
      "Use deal_watch_import_url with dryRun first before applying a shared remote watchlist.",
    ],
    recommendedPrompts: [
      "Use deal_sample_setup and show me the safest minimal config for this plugin.",
      "Use deal_template_list and recommend the right template for a price-target watch.",
      "Use deal_watch_add_template in dry-run mode to show me the exact watch config before saving it.",
      "Use deal_watch_taxonomy and tell me which saved views I should create for my current groups and tags.",
      "Use deal_host_report and show me which hosts are most active right now.",
      "Use deal_watch_add to add my first watch, then run deal_scan with commit true.",
      "Use deal_report and deal_alerts to summarize the most interesting current deals.",
      "Use deal_view_report for my saved GPU alerts view so I get a compact multi-signal report in one call.",
      "Use deal_workflow_triage to tell me what changed and what deserves attention right now.",
      "Use deal_best_price_board to show me where the best current same-product prices are across my store.",
      "Use deal_discovery_backlog to show which enabled watches are under-covered and worth expanding across more retailers.",
      "Use deal_discovery_report if I want a smaller-model-friendly discovery summary instead of raw candidate arrays.",
      "Use deal_discovery_search first when discovery.provider is firecrawl-search and you want candidate URLs from a few trusted retailer hosts.",
      "Use deal_discovery_run with explicit retailer URLs or a configured firecrawl-search provider when you want bounded discovery plus import preview.",
      "Use deal_discovery_import in dry-run mode even with provider-backed search so I can preview import decisions before changing the watchlist.",
      "Use deal_review_policy to confirm whether low-confidence scans will only queue reviews or invoke bounded auto-assist.",
      "Use deal_llm_review_queue if any watches still look ambiguous and I want a ready-to-run JSON review payload.",
      "Use deal_llm_review_run if I want one queued review executed immediately as JSON.",
      "Use deal_llm_review_apply in dry-run mode to preview how a reviewed JSON result would update my watch.",
      "Use deal_top_drops and deal_watch_insights to tell me whether my best-looking deal is actually unusual.",
    ],
    privacyAndSafety: [
      "The plugin stores watch metadata and scan history in the configured JSON store path.",
      "It only fetches http/https URLs that pass the built-in host safety policy.",
      "Use allowedHosts to narrow scanning to trusted retailer domains.",
      "Use deal_watch_export if you want a reviewable backup before making major changes.",
    ],
    troubleshooting: [
      "Use deal_doctor for a quick sanity check of config and watch coverage.",
      "Use deal_health to confirm the active fetch limits and host-policy posture.",
      "If scans return policy errors, verify the target host against allowedHosts and blockedHosts.",
      "If extraction looks weak, use deal_extraction_debug to inspect candidates, chosen fields, and confidence reasons.",
    ],
  };
}
